version: "3.3"

services:

  wordpress:
    image: wordup-wp:1.0
    build: 
      context: ${WORDUP_DOCKERFILE_WP_PATH:?err}
      args:
        USER_ID: ${WORDUP_UID:-1000}
        GROUP_ID: ${WORDUP_GID:-1000}

  wordpress-cli:  
    image: wordup-wp-cli:1.0
    build: 
      context: ${WORDUP_DOCKERFILE_WPCLI_PATH:?err}
      args:
        USER_ID: ${WORDUP_UID:-1000}
        GROUP_ID: ${WORDUP_GID:-1000}
